# Token: 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

name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Run tests
        run: ./TicketWarrior/mvnw test
        # run: ./mvnw -Dtest=UserRepositoryTest test

        # run: ./mvnw -Dtest=AuthenticationServiceTest test
        # run: ./mvnw -Dtest=NotificationServiceTest test
        # run: ./mvnw -Dtest=PurchaseServiceTest test
        # run: ./mvnw -Dtest=SeatServiceTest test
        # run: ./mvnw -Dtest=UserServiceTest test

        # run: ./mvnw -Dtest=AuthenticationIntegrationTest test
        # run: ./mvnw -Dtest=MailIntegrationTest test
        # run: ./mvnw -Dtest=PurchaseIntegrationTest test
        # run: ./mvnw -Dtest=SeatingIntegrationTest test

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build the Docker image
  #       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
