name: Docker Image CI

# Triggers on push to main branch
on:
  push:
    branches: ["main"]

jobs:
  # Job for Continuous Integration Testing Purposes
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java Development Kit
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Perform Repostitory Unit Tests
      - name: Run Repository Tests
        run: cd TicketWarrior && ./mvnw -Dtest=UserRepositoryTest test

      # Perform Service Unit Tests
      - name: Run Service Tests
        run: cd TicketWarrior && ./mvnw -Dtest=AuthenticationServiceTest test && ./mvnw -Dtest=NotificationServiceTest test && ./mvnw -Dtest=PurchaseServiceTest test && ./mvnw -Dtest=SeatServiceTest test && ./mvnw -Dtest=UserServiceTest test

      # Perform Integration Tests
      - name: Run Integration Tests
        run: cd TicketWarrior && ./mvnw -Dtest=AuthenticationIntegrationTest test && ./mvnw -Dtest=MailIntegrationTest test && ./mvnw -Dtest=PurchaseIntegrationTest test && ./mvnw -Dtest=SeatingIntegrationTest test

  # Job for Building Docker Image and pushing it to DockerHub account
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Java Development Kit
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and Tag the Docker image
        run: cd TicketWarrior && ./mvnw spring-boot:build-image && docker tag ticketwarrior:0.0.1-SNAPSHOT cerebret/cs203_project:latest

      # Need to log into Docker Hub in order to push image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Push image
        run: cd TicketWarrior && docker push cerebret/cs203_project:latest
